### ISSUE TITLE
Cannot find module '\passbolt_cli\index-auth' (Windows)

### ISSUE THREAD

**Issue by aahmadts** [passbolt/passbolt_cli#11]
After cloning the ``passbolt_cli`` and following the installation steps, passbolt cli doesn't work as expected.

So passbolt is linked well and I can check the version

```
PS C:\Users\N2GO-49\Documents\GitHub\passbolt_cli> passbolt -V
0.1.0
```

But when I try to authenticate or call and other options like `auth`, `find` I get this error:

```
PS C:\Users\E-49\Documents\GitHub\passbolt_cli> passbolt auth
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\N2GO-49\Documents\GitHub\passbolt_cli\index-auth'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

What is really strange that when I rename the `passbolt-*.js` files in the main project's directory to something like `index-*.js` it starts to work somehow.

![screenshot_2](https://user-images.githubusercontent.com/20315364/34099963-4b97a55a-e3e1-11e7-8268-085132b07a41.png)

And after renaming the files I get other error messages:

```
> passbolt auth login -p password
The server rejected the verification request.undefined
```

**Comment by Lukas8342** [comment]
node passbolt -command
