### ISSUE TITLE
Server authentication is a placebo

### ISSUE THREAD

**Issue by palant** [passbolt/passbolt_cli#12]
Note: I generally prefer reporting security issues via dedicated non-public channels. Unfortunately, I haven't found anything like that on the passbolt website. Let me know if such channels exists, I have a more sensitive issue to report as well.

Currently, passbolt has the concept of a trusted website which can trigger various actions in the extension such as decrypting a password and storing it in the clipboard. Access to this functionality should obviously be restricted as much as possible, which is probably why passbolt's login procedure has the server authenticate to the client and not merely vice versa.

Problem is, the server authentication as implemented right now is a placebo that offers nothing on top of the usual TLS mechanisms. It works by having the client send a request that only the real server can respond to correctly. However, let's assume that somebody manages to set up a fake demo.passbolt.com server (getting a valid TLS certificate somehow) and redirect client's requests to it. The attacker doesn't need to compromise the real server's key, they can simply forward the client's request to the real server and get the right response back. That's it, the client is now trusting their server and will log in. They can keep forwarding the requests to the real server in order to read the data, or they can produce their own responses in order to trigger extension functionality.

Normally, secure protocols have client and server generate a shared secret during mutual authentication, one that a Man In The Middle won't see. This secret will usually be used for encryption, or at least as an authentication token for privileged actions. Neither is really feasible the way passbolt is designed, if anything having the server sign privileged actions would be an option (not really trivial).

As it is, server authentication only makes sense if the real server is no longer available. One scenario would be the server being shut down, the domain name freed and then re-registered by an attacker. Having the server shut down while users still expect it to be present isn't a very likely scenario however. On the other hand, server authentication currently causes a major headache if the server key is compromised and needs to be replaced. Given that, maybe simply relying on TLS for server authentication and recommending additional measures such as Certification Authority Authorization is a better solution.

**Comment by palant** [comment]
I see that I created that issue in the wrong repository, I actually meant the browser extension. The command line client shares the problematic code with it however, in the file `gpgAuthController.js`. The important difference is that the command line client doesn't make server authentication visible from what I can tell, meaning that wrong expectations are less likely.

**Comment by stripthis** [comment]
Hi @palant,

You can send the more sensitive security issues to security@passbolt.com, 

017F E21B F15D 5825 6A3E  17AA 2494 727D EC92 2EA0
https://keys.mailvelope.com/pks/lookup?op=get&search=security%40passbolt.com

I will create a forum entry on https://community.passbolt.com tomorrow so that we can discuss the shortcomings of the server authentication of gpgAuth and the whole community can see it for further reference. Bottom line, you are right if TLS is broken the server authentication process is flawed.

Thanks for your interest in passbolt,

edit: replied too quick, the scenario you described is correct.

**Comment by stripthis** [comment]
https://community.passbolt.com/t/server-authentication-is-a-placebo/212

**Comment by palant** [comment]
> Bottom line, you are right if TLS is broken the server authentication process is flawed.

And if TLS isn't broken the server authentication process is unnecessary.

**Comment by stripthis** [comment]
Added a response here: https://community.passbolt.com/t/is-the-gpgauth-server-key-verification-a-placebo/212

We discussed this with the team and we arrive to the same conclusion. If TLS is broken the server authentication process is flawed. And if TLS isn’t broken the server authentication process is mostly unnecessary. As in the server key verification as you mention is only useful if the original service is shut down and registered again (or seized?), and this an edge case.

Therefore we shouldn’t advertise that the server identity is verified in the sense that we only verify if the server can use the advertised key, as it creates expectations issues. We will make that change in the next version.

Related to this problem as mentioned here, if TLS is broken, then the attacker can also add their own public key and wait/trigger a share operation where they would squeeze in their name and could then access to the decrypted password.

This is also known issue (and one of the reason why we consider passbolt in alpha) which we would like to fix with:
- Have the server sign the body of the response and adding this detached signature in the http headers: this will help make sure an attacker performing a Mim cannot add it’s key or change the list of recipient for a share operation when this list is provided by the server (used for example when getting the list “who is a member of that group”).
- Verify the other users key signatures when importing them in the keyring. We could for example have an admin sign the keys of each users as part of the registration process. This would help in the case the attacker have root access on the server and can edit the keys directly in the database.

Feel free to reach out to discuss these topics further.

**Comment by palant** [comment]
> You can send the more sensitive security issues to security@passbolt.com,

A colleague of mine found the information that I was looking for [in the FAQ under Features & Roadmap](https://www.passbolt.com/faq#roadmap). Would you consider moving this particular question to Security or Help & Support which is where I looked? Also, maybe the answer should mention security@passbolt.com rather than contact@passbolt.com?

**Comment by stripthis** [comment]
Yes that makes sense. I just updated the FAQ with the details. Thanks for pointing that out.
