### ISSUE TITLE
Clearer documentation of obtaining fingerprints

### ISSUE THREAD

**Issue by trjh** [passbolt/passbolt_cli#23]
This is probably a stupid question, as nothing on google has told me the answer, but how to I produce the sha1 fingerprints necessary for the config file?  It would be very helpful if the README.md could provide a few pointers on this.

**Comment by stripthis** [comment]
Hi there. Once you have the keys in the gnupg keyring you can do `gpg --fingerprint`.

**Comment by stripthis** [comment]
In the next version (on develop currently) I've added some functionalities to help import the server key, etc.
```
$ passbolt keyring server-public-key --display-fingerprint
$ passbolt keyring server-public-key --display-armored
```

**Comment by trjh** [comment]
Ah ok, so on my system I do:

```
% gpg --import passbolt_private.asc
% gpg --fingerprint
```

And on the server, for lack of anything more subtle...
```
$ su
# gpg --import /var/www/passbolt/config/gpg/serverkey_private.asc
# gpg --fingerprint
```

**Comment by clushie** [comment]
I was really confused about how to retrieve the server public key + fingerprint as well...
One possible solution is to go to `https://<your passbolt instance>/auth/verify.json` to get fingerprint and public key.

If you have `jq` installed you can also import the public key with this one-liner:

`curl https://<your passbolt instance>/auth/verify.json | jq -r '.body.keydata' | gpg --import`

**Comment by stripthis** [comment]
v0.5 includes a new command and some new documentation for this purpose.
