### ISSUE TITLE
No public key

### ISSUE THREAD

**Issue by dariusdev** [passbolt/passbolt_cli#25]
On mac when i try `passbolt get` command getting error: 
encryption failed: No public key

**Comment by stripthis** [comment]
You need to make sure the server public key is in your GnuPG keyring. You can get the server public key on your passbolt url domain at /auth/verify.json

Then you need to create a config file, and indicate the domain baseUrl, and the associated key fingerprints for the user and server. For example:
```
{
  "domain" : {
    "baseUrl": "http://passbolt.dev",
    "publicKey" : {
      "fingerprint" : "2FC8945833C51946E937F9FED47B0811573EE67E"
    }
  },
  "user" : {
    "firstname": "Ada",
    "lastname" : "Lovelace",
    "email" : "ada@passbolt.com",
    "privateKey" : {
      "fingerprint": "03F60E958F4CB29723ACDF761353B5B15D9B054F"
    }
  }
}
```

**Comment by dariusdev** [comment]
Then this setup information also should be in ReadMe prerequisites. 
Thanks for your help :) Now just need to find out how to add this thing to gpg keyring.

**Comment by stripthis** [comment]
Yes I agree the setup is not very user friendly right now.
On the develop branch I also made some work to grab the server key with one command. Hopefully i'll get the time to merge all this soon.

**Comment by dariusdev** [comment]
After successful import step it asks me: 

gpg: decryption failed: No secret key

i should import my account private key also into gpg?

**Comment by stripthis** [comment]
Yes
