### ISSUE TITLE
async checkstatus syntaxerror

### ISSUE THREAD

**Issue by jerheij** [passbolt/passbolt_cli#27]
I have followed the instructions from the readme but I get the following error on two of my Linux systems:

> /git/passbolt_cli/app/controllers/gpgAuthController.js:49
>   async checkStatus() {
>         ^^^^^^^^^^^
> 
> SyntaxError: Unexpected identifier
>     at createScript (vm.js:56:10)
>     at Object.runInThisContext (vm.js:97:10)
>     at Module._compile (module.js:549:28)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/git/passbolt_cli/passbolt-auth.js:10:25)
>     at Module._compile (module.js:577:32)
> 

I tested this on a WSL Ubuntu with the following kernel: _4.4.0-17763-Microsoft_ and on a CentOS 7 with the following kernel: _3.10.0-957.21.3.el7.x86_64_

I had to change the index.js to _#!/usr/bin/node_ to even get the error, I also tested it without the _--harmony_ parameter but same result.

**Comment by stripthis** [comment]
Hello @jerheij, which version of nodejs are you using? I think there might be an issue with Async support for node < 8.

**Comment by jerheij** [comment]
On the WSL **v4.2.6** and on the CentOS 7 machine **v6.17.1**.

**Comment by stripthis** [comment]
Unfortunately the requirement for this project is Nodejs LTS or higher (10 LTS or 12 stable).

**Comment by jerheij** [comment]
Ah, I see, I installed version 10 on the CentOS machine and it seems to work now. Thanks!

Just a question/suggestion: wouldn't most distributions use /usr/bin/node as default? If so, wouldn't it be better to change the interpreter in index.js to that executable?
