### ISSUE TITLE
Nodejs UnhandledPromiseRejectionWarning:

### ISSUE THREAD

**Issue by jerheij** [passbolt/passbolt_cli#28]
As stated in my previous ticket I got the NodeJS working but now there is a UnhandledPromiseRejectionWarning:

> [root@srv01 passbolt_cli]# passbolt auth <user> --verbose
> GET http://192.168.199.246:8080/auth/checkSession.json
> 403
> Please enter the one time password displayed on your tablet or phone.
> otp: <CODE>
> (node:21571) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
>     at cookieStore.findCookie (/git/passbolt_cli/app/controllers/gpgAuthController.js:129:26)
>     at FileCookieStore.findCookie (/git/passbolt_cli/node_modules/tough-cookie-file-store/lib/file-store.js:32:16)
>     at Promise (/git/passbolt_cli/app/controllers/gpgAuthController.js:125:24)
>     at new Promise (<anonymous>)
>     at GpgAuthController.getCsrfToken (/git/passbolt_cli/app/controllers/gpgAuthController.js:120:12)
>     at GpgAuthController.mfaVerify (/git/passbolt_cli/app/controllers/mfaController.js:60:34)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:21571) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejec
> tion id: 2)
> (node:21571) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by stripthis** [comment]
We're releasing a new version of the API / Extension tomorrow, I'll double check for MFA issues right after.

**Comment by stripthis** [comment]
I'm unable to reproduce this issue. Please try again with v0.5 and reopen a new issue with more information about your environment if the problem persists.
