### ISSUE TITLE
`passbolt auth check` always returns 403

### ISSUE THREAD

**Issue by JenChampagne** [passbolt/passbolt_cli#29]
When I use the command `passbolt auth login --verbose` and enter my passphrase, I get all `200`s with the message `GPGAuth you are now logged in`.

However, when I use the command `passbolt auth check --verbose` I get a response of `403` with a message of `You are not logged in.`.

I suspect it is related to cookieJar / `tough-cookie`, as the file `./app/tmp/cookie.json` is touched each time I login, but the file is always empty without exception.

I added some extra console logging to `login` in `gpgAuthController` and I can see the variable `cookie` contains `Cookie="CAKEPHP=4o99fiikd5bb8dv6u4s2df3ub3; Path=/; Secure; HttpOnly; hostOnly=?; aAge=?; cAge=0ms"` but as I said, the `cookie.json` file stays empty.

Any suggestions would be appreciated. I'm using the repo on a MacBook.

**Comment by stripthis** [comment]
Hi @JenChampagne can you confirm that you have MFA enabled on this account?

**Comment by stripthis** [comment]
This should be fixed with v0.5 released today.

**Comment by JenChampagne** [comment]
I was able to locally fix the issue by fixing an error in `tough-cookie-file-store` in which the cookie writing method is an unbound async file write, and I suspect the passbolt cli was terminating before the file write was ever executed.

After changing the file write in that module to be synchronous, everything worked as expected.

Nothing to do with your library in the end! Sorry for the late reply.

**Comment by JenChampagne** [comment]
I wonder if maybe there is a forced `process.exit` causing the file write to not complete?

**Comment by stripthis** [comment]
> I wonder if maybe there is a forced process.exit causing the file write to not complete?

Yes that was the case, I removed them in version 0.5 published yesterday.

**Comment by JenChampagne** [comment]
Awesome, thank you! Great utility as well 👍
