### ISSUE TITLE
Error: Could not connect

### ISSUE THREAD

**Issue by pblajev** [passbolt/passbolt_cli#3]
I have passbolt-1.6.1 running on CentOS7.3. It is in use by a dozen people in the office without a problem.

I installed nodejs v.8.3.0 (I also tried v.6 but got the same error).

When I try to authenticate I'm getting 'could not connect error':

# passbolt auth peter@mydomain.com
Error: could not connect to https://sdo-passwords.mydomain.com/auth/verify.json

I can get the file if I run:

# curl -k https://sdo-passwords.mydomain.com/auth/verify.json

Is this because I'm using self-signed cert?
Or, I'm just missing something?

NOTE: I was referred to  https://github.com/passbolt/passbolt_api/issues/141 but It doesn't seem to be the same problem. Also I already have rng-tools installed.

Thank you,
-- Peter

**Comment by stripthis** [comment]
Hi peter, thank you for the detailed report.
Could you try to run the following see if we can get more details:
`
passbolt auth --verbose
`

On a side note you should not have to specify the user (e.g. peter@mydomain.com), as this would be defined in config.json. Maybe you got confused because in the readme you can see `passbolt auth -p ada@passbolt.com` but this email is actually the password (e.g. `-p, --passphrase`) of our test  profiles such as ada, betty, carole, etc. (I know it's confusing, i'll make it more clear).

Your config file should look like this:
```
{
  "domain" : {
    "baseUrl": "http://passbolt.dev",
    "publicKey" : {
      "fingerprint" : "SERVER_KEY_FINGERPRINT"
    }
  },
  "user" : {
    "firstname": "peter",
    "lastname" : "something",
    "email" : "peter@mydomain.com",
    "privateKey" : {
      "fingerprint": "YOUR_PUBLIC_KEY_FINGERPRINT"
    }
  }
}
```

I hope this helps. Let's see if there is another issue.

**Comment by pblajev** [comment]
Hi Remy,

Thank you for the response.

Here is what I did and I hope this helps:

----
Installed NodeJS and passbolt_cli

# passbolt --help
/usr/bin/env: node --harmony: No such file or directory

I don't know if that matters but to get around the above error I edited
/opt/passbolt_cli/index.js file and removed /usr/bin/env:
#!/usr/bin/node --harmony

---
cat /opt/passbolt_cli/app/config/config.json
{
  "domain" : {
    "baseUrl": "https://sdo-passwords.mydomain.com",
    "publicKey" : {
      "fingerprint" : "880F059FAFCC390595CBE97CA78A337D4E1C386E"
    }
  },
  "user" : {
    "firstname": "Peter",
    "lastname" : "Blajev",
    "email" : "pblajev@mydomain.com",
    "privateKey" : {
      "fingerprint": "60F029D945D4915AA55437C2B722265B2C1B7F7D"
    }
  }
}

The server fingerprint is the same as the one in app.php file.
I get my fingerprint when I login to passbolt -> "manage your keys" page.

----
# passbolt auth --verbose
No authentication cookie found
GPGAuth login start with fingerprint
60F029D945D4915AA55437C2B722265B2C1B7F7D
POST https://sdo-passwords.mydomain.com/auth/verify.json
GPGAuth Error during login
Error: could not connect to
https://sdo-passwords.mydomain.com/auth/verify.json
#

Thank you,

-- Peter

**Comment by stripthis** [comment]
Hi @pblajev, I could reproduce the issue with self-signed certifcates. I added an option in v0.1.0 that you can add in the configuration file that should do the (less secure) trick:
`
  "agentOptions": {
    "rejectUnauthorized": true
  }
`

**Comment by pblajev** [comment]
Hey Remy,

I pulled the latest changes and added the new options but now I'm getting
an error.

# cat /opt/passbolt_cli/app/config/config.json
{
  "domain" : {
    "baseUrl": "https://sdo-passwords.mydomain.com",
    "publicKey" : {
      "fingerprint" : "880F059FAFCC390595CBE97CA78A337D4E1C386E"
    }
  },
  "user" : {
    "firstname": "Peter",
    "lastname" : "Blajev",
    "email" : "pblajev@mydomain.com",
    "privateKey" : {
      "fingerprint": "60F029D945D4915AA55437C2B722265B2C1B7F7D"
    }
  }
  "gpg" : {
    "trust": "always"
  }
  "agentOptions": {
    "rejectUnauthorized": "true"
  }
}
#
#
# passbolt auth -v
/opt/passbolt_cli/app/models/user.js:83
    if (config.user.privateKey === undefined) {
                   ^
TypeError: Cannot read property 'privateKey' of undefined
    at User.__loadDefault (/opt/passbolt_cli/app/models/user.js:83:20)
    at new User (/opt/passbolt_cli/app/models/user.js:29:20)
    at GpgAuthController._parseProgramArg (/opt/passbolt_cli/app/
controllers/gpgAuthController.js:209:19)
    at new GpgAuthController (/opt/passbolt_cli/app/
controllers/gpgAuthController.js:26:10)
    at Object.<anonymous> (/opt/passbolt_cli/passbolt-auth.js:29:15)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
#


Thank you,
-- Peter

**Comment by stripthis** [comment]
Hi @pblajev,

You are missing some commas in your config file:
```
{
    "domain" : {
        "baseUrl": "https://sdo-passwords.mydomain.com", 
         "publicKey" : { "fingerprint" : "880F059FAFCC390595CBE97CA78A337D4E1C386E" }
    },               
    "user" : {
        "firstname": "Peter",
        "lastname" : "Blajev",
        "email" : "pblajev@mydomain.com",
        "privateKey" : {
            "fingerprint": "60F029D945D4915AA55437C2B722265B2C1B7F7D"
        }
    },
    "gpg" : { 
        "trust": "always" 
    },
    "agentOptions": {
        "rejectUnauthorized": "true"
    }
}
```

This is a json file so the options must be separated with commas (e.g. before "gpg" and "agentOptions"). That should resolve your issue.

**Comment by pblajev** [comment]
Hey Remy,

That worked great.

Thank you,
-- Peter
