### ISSUE TITLE
How to use with a Client-Side Certificate ?

### ISSUE THREAD

**Issue by NRGLine4Sec** [passbolt/passbolt_cli#31]

**Comment by stripthis** [comment]
You can use agentOptions in the config. See the readme and in particular: https://github.com/request/request#using-optionsagentoptions

**Comment by NRGLine4Sec** [comment]
Thanks for your quick response.
Can you give me an exemple with the agentOptions yout talk about with [exemple configuration](https://github.com/passbolt/passbolt_cli#example-configuration) because I tried it myself and it doesn't work.

**Comment by stripthis** [comment]
I think you need to put the content of the file in the json config rather than using fs. I have not personally tried it, so I can't give you more precise direction but I think it should work.

**Comment by NRGLine4Sec** [comment]
currently I have tried to had the following : 
```
const fs = require('fs')
    , path = require('/home/test/Bureau')
    , certFile = path.resolve(__dirname, 'user.crt')
    , keyFile = path.resolve(__dirname, 'user.key')
    , request = require('request');

const options = {
    url: 'https://passbolt.test.test/',
    agentOptions: {
        cert: fs.readFileSync(certFile),
        key: fs.readFileSync(keyFile),
        // Or use `pfx` property replacing `cert` and `key` when using private key, certificate and CA c$
        // pfx: fs.readFileSync(pfxFilePath),
        passphrase: 'cert',
    }
};

request.get(options);
```
at the beginning of config.json, but i'm not good with JavaScript and NPM so I can't really debug it.

**Comment by stripthis** [comment]
Config.json is not an executable, so it cannot work. You will need to to write valid JSON.
like:
```
{
  "domain" : {
    "baseUrl": "https://www.passbolt.test",
    "publicKey" : {
      "fingerprint" : "2FC8945833C51946E937F9FED47B0811573EE67E"
    }
  },
  "user" : {
    "firstname": "Ada",
    "lastname" : "Lovelace",
    "email" : "ada@passbolt.com",
    "privateKey" : {
      "fingerprint": "03F60E958F4CB29723ACDF761353B5B15D9B054F"
    }
  },
  "agentOptions": {
    "rejectUnauthorized": false,
     "cert" : "the actual content of the file...",
     "etc.": "more content..."
  }
}

**Comment by NRGLine4Sec** [comment]
Thanks ! I will tried it.
