### ISSUE TITLE
Sporadic sign outs after ~60 min

### ISSUE THREAD

**Issue by TobiKr** [passbolt/passbolt_cli#32]
Several users complain a sporadic sign out of the session after about 60 Minutes and have to re-enter the password to decrypt passwords in both web gui and browser extension.

Version: 2.12
passbolt.php session config:
`// Session configuration.
    'Session' => [
        'defaults' => 'php',
        // Session timeout in minutes.
        'timeout' => 720,
        'ini' => [
            'session.gc_maxlifetime' => 43200,
            'session.cookie_lifetime' => 43200
        ]
    ],
`
Sessions
Browser Plugin Version: 2.12
Browsers affected: Chrome (latest) and Firefox (latest)
How can we debug that issue?
Thanks
Tobias

**Comment by stripthis** [comment]
You can discuss configuration issues on the community forum: https://community.passbolt.com/ as this space is reserved for CLI bugs. Thanks,
