### ISSUE TITLE
no option to create a new secret using CLI

### ISSUE THREAD

**Issue by SinghDivneet** [passbolt/passbolt_cli#37]
In the readme file couldn't find any option to create a new secret after logging in

**Comment by stripthis** [comment]
@SinghDivneet yes it's correct, it's not present at the moment. You can use other community based projects for this however. such as https://github.com/liip/wrench

**Comment by stripthis** [comment]
You can request new features on the community forum, we use github only for bugs: https://community.passbolt.com/t/a-way-to-change-a-password-or-create-new-password-with-a-cli-in-passbolt/1247/2
