### ISSUE TITLE
After upgrade passbolt to 3.1.0 cli returns error 500 could not parse server response.

### ISSUE THREAD

**Issue by beer1970** [passbolt/passbolt_cli#42]
$ node -v                      
v14.16.0
  $ passbolt users
(node:53535) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Error 500 could not parse server response.

**Comment by stripthis** [comment]
Hi @beer1970,

Thanks for the report, i'll have a look.

**Comment by stripthis** [comment]
Fixed with 0.6.0. Feel free to open a new ticket if you have some issues.
