### ISSUE TITLE
/usr/bin/env: 'node --harmony': No such file or directory

### ISSUE THREAD

**Issue by streamcoindev** [passbolt/passbolt_cli#6]
im getting /usr/bin/env: 'node --harmony': No such file or directory
 when trying to run passbolt or directly executing the index.js

**Comment by stripthis** [comment]
Hi, most likely the node binary is not on your $PATH.
https://duckduckgo.com/?q=%2Fusr%2Fbin%2Fenv%3A+%27node+--harmony%27%3A+No+such+file+or+directory&t=ffsb&ia=web

**Comment by sheoak** [comment]
I have node in my path but still have this error. This is due to the _--harmony_ parameter. 

I understand that the parsing of the shebang depends on the Linux distributions because the implementation is free.

```
$ uname -r
4.19.2-arch1-1-ARCH
```

Removing it fixes the problem but I suppose it's there for older node versions?

**Comment by maxtruxa** [comment]
The fact that the optional argument in the Shebang is passed as a single string is mentioned in this [Wikipedia article](https://en.wikipedia.org/wiki/Shebang_(Unix)#Portability):
> Some systems, including Linux, do not split up the arguments; for example, when running the script with the first line like,
>
> ```
> #!/usr/bin/env python -c
> ```
> That is, `python -c` will be passed as one argument to `/usr/bin/env`, rather than two arguments.

What this means is that if you try to run the `index.js` using the system's native loader, `/usr/bin/env` looks for a binary called `node --harmony` which obviously doesn't exist. This is the case for example if you install `passbolt_cli` globally and the run the `passbolt` command.

With somewhat recent versions of Node.js `--harmony` probably isn't necessary anymore anyways, right?
