### ISSUE TITLE
Open the blank passbolt page

### ISSUE THREAD

**Issue by chyff** [passbolt/passbolt_cli#60]
Open passbolt as a blank page in Firefox. Google opens the page normally. Firefox version 113.0.2 is available

**Comment by cedricalfonsi** [comment]
Hello @chyff.

You reported on the wrong github, this github is related to the command line passbolt tool. Issue relative to the browser extension can be reported here: https://github.com/passbolt/passbolt_browser_extension.

If you are running an API < 3.0, checkout this issue reported on the community forum: https://community.passbolt.com/t/passbolt-extension-chrome-notfounderror-after-v4-upgrade-testing-from-2-7-1/7405
