### ISSUE TITLE
gpg secret key not found 

### ISSUE THREAD

**Issue by streamcoindev** [passbolt/passbolt_cli#7]
Where does passbolt_cli search for its gpg secret key since i keep getting
[Error: gpg: encrypted with RSA key, ID 4110313A
gpg: decryption failed: secret key not available
]
gpg: encrypted with RSA key, ID 4110313A
gpg: decryption failed: secret key not available
but the secret keys are available in passbolt api directories

**Comment by stripthis** [comment]
Hi, 

Passbolt CLI uses the GPG keyring locally available ($GNUPGHOME most likely in ~/.gnupg). passbolt_cli does not share data with the passbolt_api. You should not store secret keys in passbolt api directories unless it is the server key.

**Comment by streamcoindev** [comment]
i checked and this key 4110313A  does not exist in the keyring at all the only key that exist in the keyring is the key that is used for everything the server etc however that key has another id i tried passbolt auth i tried passbolt auth priv.key i tried passbolt auth -p password here i have only 1 user 1 json .conf and 1 key but still i cant get past this error

**Comment by stripthis** [comment]
Hi @lanaiscool 
There can be multiple issues that make your setup fails, like an invalid hostname, the fact that the second machine cannot connect to the server, etc. it is hard to guess which one it is in your case.

For passbolt cli to work you need to:
- Install passbolt API server . 
- Register a user on in the API server
- Follow the setup for that user, you export the secret key of that user for later use
- On the machine running passbolt cli you install gpg and create a gpg keyring
- Import your user key in this keyring
- Install nodejs and run a Npm install
- You add the key and user information to the passbolt config

**Comment by streamcoindev** [comment]
i think i did something very wrong i installed passbolt_cli on the same server where the passbolt api is ruuning also in the passbolt config do i paste the fingerprint of the user or the whole private key ?

**Comment by stripthis** [comment]
Hi @lanaiscool yes passbolt_cli is supposed to be used a client. For the config you only need to add the fingerprint. There is an example file (see "ada lovelace" credentials) in the config folder.

**Comment by streamcoindev** [comment]
yes i fixed it and imported it however  still getting that events.js error  are there any ports that need to be open to the outside ?

**Comment by stripthis** [comment]
Which domain and which port are you using?

**Comment by streamcoindev** [comment]
im using https://vault.hostingforyou.nl 
in the config
