### ISSUE TITLE
events.js error list of dependecies ?

### ISSUE THREAD

**Issue by streamcoindev** [passbolt/passbolt_cli#8]
im getting a events.js error am i missing any modules or something ? is there a list op dependecies i need to ensure passsbolt_cli will work
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at WriteWrap.afterWrite (net.js:763:14)

**Comment by stripthis** [comment]
Hi all the dependencies are listed in the package.json and should be installed if you do a npm install. By the look of your error you have an issue with your host / hostPort.

**Comment by streamcoindev** [comment]
there is no firewall in between the servers and i can do a wget just fine over https from one server to another

**Comment by stripthis** [comment]
Is it a self signed certificate?

**Comment by streamcoindev** [comment]
it is a wildcard certificate

**Comment by streamcoindev** [comment]
still having this issue like i had months back and i have no clue how to solve it

**Comment by stripthis** [comment]
Can you provide some information on how to reproduce the issue? Like which operating system do you use? Which node version do you use? Do you have the same issue with another server like demo.passbolt.com?

**Comment by streamcoindev** [comment]
Yeah sure thing first of all my system
Ubuntu 16.04 server php 7  base url = https://vault.hostingforyou.nl
And my config file for the cli looks like this:

{
  "domain" : {
    "baseUrl": "https://vault.hostingforyou.nl",
    "publicKey" : {
      "fingerprint" : "fingerprinthere"
    }
  },
  "user" : {
    "firstname": "myFirtsname",
    "lastname" : "hoesel",
    "email" : "n.vanhoesel@hostingforyou.nl",
    "privateKey" : {
      "fingerprint": "fingerprinthere"
    }
}
}

also can i just use demo.passbolt.com ?

**Comment by stripthis** [comment]
@lanaiscool you can use demo.passbolt.com to find out if you are having an issue with your local system or the server configuration. Do not use it to store passwords.

**Comment by streamcoindev** [comment]
Found something interesting after i reboot the server and try to login
@h4y-vault:~$ sudo su -s /bin/bash -c "passbolt auth login -p passhere" www-data
[sudo] password for h4yadm: 
gpg: D0A5D96B: There is no assurance this key belongs to the named user
gpg: [stdin]: encryption failed: unusable public key

but every try after that will result in this : until i reboot server

@h4y-vault:~$ sudo su -s /bin/bash -c "passbolt auth login -p passhere" www-data
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at WriteWrap.afterWrite (net.js:763:14)

**Comment by stripthis** [comment]
Are you running the CLI on the same server hosting passbolt? The CLI is meant to be used on another machine, i'm not sure how it behaves when looping back on itself.

**Comment by streamcoindev** [comment]
Ohh yes i am indeed using passbolt_cli on the same server will try it on another machine

**Comment by streamcoindev** [comment]
what keys do i need to insert into my local keyring on the other machine ? the serverkey and user key ?

**Comment by stripthis** [comment]
To use the CLI you need the user secret key and the server public key in the gnupg keyring.

**Comment by streamcoindev** [comment]
getting the same i try to login using passbolt auth login -p then i get 
gpg: D0A5D96B: There is no assurance this key belongs to the named user
gpg: [stdin]: encryption failed: unusable public key

every try after that will result in an events.js error as described above until i reboot the machine where i ran the Cli

**Comment by streamcoindev** [comment]
It has something todo with keys from gpg2 and passbolt_cli is using gpg1

**Comment by streamcoindev** [comment]
fixed it by adding trust level 5 passbolt is working now
