### ISSUE TITLE
As a user I should see a user friendly message if the config file is missing

### ISSUE THREAD

**Issue by candlerb** [passbolt/passbolt_cli#9]
[README.md](https://github.com/passbolt/passbolt_cli/blob/master/README.md) says:

> Create or copy a configuration file with a user and a server config
> ```
> cd app/config
> cp config.default.json
> ```

But that's invalid use of `cp`, as it doesn't include the destination filename.  I'm no JS hacker but looking at source I think it should be:

~~~
cp config.default.json config.json
~~~

Incidentally, if config.json doesn't exist, then you get a nodejs backtrace which isn't very friendly:

~~~
$ passbolt auth
/Users/brian/git/passbolt_cli/app/models/user.js:83
    if (config.user.privateKey === undefined) {
                   ^

TypeError: Cannot read property 'privateKey' of undefined
    at User.__loadDefault (/Users/brian/git/passbolt_cli/app/models/user.js:83:20)
    at new User (/Users/brian/git/passbolt_cli/app/models/user.js:29:20)
...
~~~

(whereas "Unable to open /app/config/config.json" would have been more helpful)

**Comment by stripthis** [comment]
I agree, thank you for the feedback!

**Comment by candlerb** [comment]
Stunningly fast response. Thank you ! 👍
